version: "3.7"
services:
  webapp:
    container_name: webapp
    build: ./nginx
    volumes:
      - ../src:/var/www/localhost
    ports:
      - 8080:80
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    build: ./php-fpm
    environment:
      - "XDEBUG_HOST=${MY_IP_ADDR}"
    volumes:
      - ../src:/var/www/localhost